# Example Best Hyperparameters from Optuna Tuning
# This file shows the format of optimized hyperparameters
# Actual values will differ based on data and optimization results

hidden_layers:
  - units: 256
    activation: relu
    dropout_rate: 0.12
    batch_norm: true
  - units: 128
    activation: tanh
    dropout_rate: 0.08
    batch_norm: false

learning_rate: 0.00234
batch_size: 16
l2_regularization: 0.0001
ls_decay_rate: 5.0
ls_reduction_factor: 0.5

# Optuna study metadata
best_trial_number: 87
best_value: -38.92  # Negative log-likelihood
n_trials_completed: 128
optimization_time_seconds: 25847
